menu:
    Blog: /
    Archive: /archives/
    Weibo: https://weibo.com/u/2012726081
    GitHub: https://github.com/leejersey
    Rss: /atom.xml

favicon: favicon.png
logo: favicon.png
avatar: favicon.png

# Comment
disqus:

gitalk:
    on: false
    clientID:
    clientSecret:
    owner:
    admin:
    repo:

# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Information
startyear: 2015
